spring:
  application:
    name: gesti-bank-backend

  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  cloudinary:
    url: ${CLOUDINARY_URL}
    upload:
      base-folder: /bank-demand-management/

logging:
  level:
    org:
      springframework:
        security: debug